#!/bin/bash

# GitHub + Azure Static Web Apps Setup Script
# This script helps set up automated deployment

echo "🚀 GitHub + Azure Static Web Apps Setup"
echo "======================================="
echo ""

echo "📋 Prerequisites:"
echo "1. GitHub account"
echo "2. Azure subscription with Static Web App created"
echo "3. Domain: www.agave-nv.com"
echo ""

echo "🔧 Step 1: Create GitHub Repository"
echo "=================================="
echo "1. Go to https://github.com/new"
echo "2. Repository name: agave-nv-website"
echo "3. Description: Agave New Ventures Coming Soon Website"
echo "4. Make it PUBLIC (required for free Azure Static Web Apps)"
echo "5. DON'T initialize with README, .gitignore, or license"
echo "6. Click 'Create repository'"
echo ""

echo "📤 Step 2: Push Code to GitHub"
echo "=============================="
echo "After creating the repository, run these commands:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/agave-nv-website.git"
echo "git push -u origin main"
echo ""

echo "🔗 Step 3: Connect Azure to GitHub"
echo "================================="
echo "1. Go to https://portal.azure.com"
echo "2. Navigate to Static Web App: agave-nv-coming-soon"
echo "3. Go to 'Deployment' → 'Deployment source'"
echo "4. Click 'GitHub' → 'Authorize with GitHub'"
echo "5. Select repository: agave-nv-website"
echo "6. Branch: main"
echo "7. Build Presets: Custom"
echo "8. App location: /"
echo "9. API location: (leave empty)"
echo "10. Output location: (leave empty)"
echo "11. Click 'Review + Create'"
echo ""

echo "🌐 Step 4: Configure Custom Domain"
echo "================================="
echo "1. In Azure Portal → 'Custom domains'"
echo "2. Click 'Add custom domain'"
echo "3. Enter: www.agave-nv.com"
echo "4. Choose CNAME validation"
echo "5. Add DNS record:"
echo "   Type: CNAME"
echo "   Name: www"
echo "   Value: agave-nv-coming-soon.azurestaticapps.net"
echo "   TTL: 300"
echo ""

echo "✅ Step 5: Automatic Deployment"
echo "=============================="
echo "Once connected, every push to main branch will:"
echo "- Automatically build and deploy your website"
echo "- Update www.agave-nv.com with latest changes"
echo "- Provide staging environments for pull requests"
echo ""

echo "🎉 Benefits of GitHub + Azure:"
echo "============================="
echo "✅ Automatic deployments on code changes"
echo "✅ Staging environments for testing"
echo "✅ Pull request previews"
echo "✅ Version control and collaboration"
echo "✅ Free hosting with custom domain"
echo "✅ Automatic SSL certificates"
echo ""

echo "📞 Need help? Contact: info@agave-nv.com"
echo ""
echo "🌐 Your site will be live at: https://www.agave-nv.com"

